# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default

app:
  name: container-registry
  healthCheckPath: /health
  profile:
  replicaCount: 1
  hostAliases: []
  image: idock.daumkakao.io/cloud-service/sample:latest
  resources: {}
  service:
    type: NodePort
    nodePort:
  ingress:
    enabled: false
    annotations: {}
    hosts: []
    tls:
      enabled: false
      secretName:
