# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default

app:
  profile: stg
  image: idock.daumkakao.io/cloud-service/sample:stg
  replicaCount: 5
  service:
    type: ClusterIP
    nodePort:
  ingress:
    enabled: true
    hosts:
      - host: www.sample.com
        paths:
          - /
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.org/server-snippets: |
        error_page 400 404 405 /40x.html;
        location /40x.html{
          proxy_pass https://console.sandbox.kakaoi.io;
        }
        error_page 500 505 /50x.html;
        location /50x.html{
          proxy_pass https://console.sandbox.kakaoi.io;
        }
