# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default

app:
  profile: dev
  service:
    type: NodePort
    nodePort: 30080
