# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fluentd:
  image: idock.daumkakao.io/cloud-service/cr-fluentd:v1.15-debian-arm64-mongo-1
  scrapNamespace: cr-registry
  logType: docker

db:
  host: 192.168.50.228
  image:
    registry: docker.io
    repository: bitnami/mongodb
    tag: 6.0.2-debian-11-r1
