# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fluentd:
  image: gitlab-registry.gov.kakaoicloud.com/csap-cloud/kic-services/cr-fluentd:v1.15-debian-mongo-1