CREATE TABLE T_PROJECT
(
    ID               VARCHAR(100) NOT NULL COMMENT '프로젝트ID',
    PROJECT_NAME     VARCHAR(100) NOT NULL COMMENT '프로젝트이름',
    DOMAIN_NAME      VARCHAR(100) NOT NULL COMMENT '도메인이름',
    DOMAIN_ID        VARCHAR(100) NOT NULL COMMENT '도메인ID',
    CREATED_BY       VARCHAR(100) NULL     COMMENT '생성자ID',
    CREATED_DT       TIMESTAMP    NULL     COMMENT '생성일시',
    UPDATED_BY       VARCHAR(100) NULL     COMMENT '수정자ID',
    UPDATED_DT       TIMESTAMP    NULL     COMMENT '수정일시',
    PRIMARY KEY (ID)
) COMMENT '프로젝트';

CREATE TABLE T_SAMPLE
(
    ID             VARCHAR(100) NOT NULL,
    PROJECT_ID     VARCHAR(100) NOT NULL,
    NAME           VARCHAR(100) NOT NULL,
    DESCRIPTION    VARCHAR(255) NULL,
    CREATED_BY     VARCHAR(100) NULL,
    CREATED_DT     TIMESTAMP    NULL,
    UPDATED_BY     VARCHAR(100) NULL,
    UPDATED_DT     TIMESTAMP    NULL,
    PRIMARY KEY (ID)
) COMMENT '샘플';

ALTER TABLE T_SAMPLE
    ADD CONSTRAINT FK_T_PROJECT_TO_T_SAMPLE
        FOREIGN KEY (PROJECT_ID)
            REFERENCES T_PROJECT (ID);

CREATE TABLE shedlock (
    name       VARCHAR(64)  NOT NULL,
    lock_until TIMESTAMP(3) NOT NULL,
    locked_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    locked_by  VARCHAR(255) NOT NULL,
    PRIMARY KEY (name)
);
