## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  adminPassword: password1234

  ingress:
    enabled: true
    hosts: ["grafana.container-registry.p.k5d.io"]
    ingressClassName: "nginx"

  serviceMonitor:
    enabled: false

  persistence:
    enabled: true
    storageClassName: general

## Component scraping the kube api server
##
kubeApiServer:
  enabled: false

## Component scraping the kubelet and kubelet-hosted cAdvisor
##
kubelet:
  enabled: true

## Component scraping the kube controller manager
##
kubeControllerManager:
  enabled: false

## Component scraping coreDns. Use either this or kubeDns
##
coreDns:
  enabled: false

## Component scraping kubeDns. Use either this or coreDns
##
kubeDns:
  enabled: false

## Component scraping etcd
##
kubeEtcd:
  enabled: false

## Component scraping kube scheduler
##
kubeScheduler:
  enabled: false

  serviceMonitor:
    enabled: false

## Component scraping kube proxy
##
kubeProxy:
  enabled: false

## Configuration for kube-state-metrics subchart
##
kube-state-metrics:
  image:
    repository: cr.undercloud.io/devii/libs/kube-state-metrics
    tag: v2.7.0

  prometheus:
    monitor:
      enabled: true

  selfMonitor:
    enabled: false

## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  enabled: true

  kubeletService:
    enabled: true

## Deploy a Prometheus instance
##
prometheus:

  enabled: true

  ingress:
    enabled: true

    hosts: ["prometheus.container-registry.p.k5d.io"]

    ingressClassName: "nginx"

  serviceMonitor:
    selfMonitor: false

  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: general
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
