## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  adminPassword: password1234

  ingress:
    enabled: true
    hosts: ["grafana.local"]
    ingressClassName: "nginx"

  serviceMonitor:
    enabled: false

## Component scraping the kube api server
##
kubeApiServer:
  enabled: false

## Component scraping the kubelet and kubelet-hosted cAdvisor
##
kubelet:
  enabled: true

## Component scraping the kube controller manager
##
kubeControllerManager:
  enabled: false

## Component scraping coreDns. Use either this or kubeDns
##
coreDns:
  enabled: false

## Component scraping kubeDns. Use either this or coreDns
##
kubeDns:
  enabled: false

## Component scraping etcd
##
kubeEtcd:
  enabled: false

## Component scraping kube scheduler
##
kubeScheduler:
  enabled: false

  serviceMonitor:
    enabled: false

## Component scraping kube proxy
##
kubeProxy:
  enabled: false

## Configuration for kube-state-metrics subchart
##
kube-state-metrics:
  prometheus:
    monitor:
      enabled: true

  selfMonitor:
    enabled: false

## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  enabled: true

  kubeletService:
    enabled: true

  ## Prometheus-operator image
  ##
  image:
    registry: quay.io
    repository: prometheus-operator/prometheus-operator
    tag: v0.60.1
    sha: ""
    pullPolicy: IfNotPresent

  ## Prometheus-config-reloader
  ##
  prometheusConfigReloader:
    image:
      registry: quay.io
      repository: prometheus-operator/prometheus-config-reloader
      tag: v0.60.1
      sha: ""

    # resource config for prometheusConfigReloader
    resources:
      requests:
        cpu: 200m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 50Mi

## Deploy a Prometheus instance
##
prometheus:

  enabled: true

  ingress:
    enabled: true
    hosts: ["prometheus.local"]
    ingressClassName: "nginx"

  serviceMonitor:
    selfMonitor: false

  prometheusSpec:
    image:
      registry: quay.io
      repository: prometheus/prometheus
      tag: v2.39.1
      sha: ""


